version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_social_api
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  data: {}
